---
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt: pkg={{ item }} update-cache=yes
      with_items: "{{ system_packages }}"

    - name: Create directory for app
      file: path={{ install_root }}/{{ project_name }} state=directory

    - name: Install Nodejs PPA
      shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

    - name: Install Nodejs
      apt:
        name: nodejs
        update_cache: yes

    - name: Install build-essential
      apt:
        name: build-essential
        update_cache: yes

    - name: install pm2
      shell: npm install pm2@latest -g

    - name: install node-gyp
      shell: npm install -g node-gyp

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default state=absent

- include: deploy.yml

# vim:ft=ansible: